__title__ = "mypackage"
__version__ = "0.0.1"
__author__ = "Sebastian Belmonte"
__email__ = "sebastian@email.com"
__description__ = "this is mypackage description"
__url__ = "https://github.com/SebastianBelmonte95/mypackage"
__license__ = "MIT License"
